In [1]:
import pandas as pd
import glob

In [58]:
files=glob.glob('../data/*.xlsx')
files

['../data/~$SCI4climate_VERSAND.xlsx', '../data/SCI4climate_VERSAND.xlsx']

In [59]:
data=pd.read_excel(files[0],skiprows=2,dtype={"Postleitzahlgebiet":str})

ValueError: Excel file format cannot be determined, you must specify an engine manually.

In [60]:
data.columns

Index(['Postleitzahlgebiet', 'Transformationsindex Infrastrukturrelevanz',
       'Industriestandorte für CCS-Anwendungen',
       'Industriestandorte für Wasserstoffanwendungen',
       'Windkraftanlagen Neubau',
       'Stromtrassen-Übertragungssnetze (oberiridisch)',
       'CO2-Hauptleitung Neubau', 'Wasserstoffkernnetz Umbau ',
       'Wasserstoffkernnetz Neubau ',
       'Stromtrassen-Übertragungsnetze (unterirdisch)', 'Solarparks Neubau',
       'Unnamed: 11', 'Transformationsindex Infrastrukturrelevanz.1',
       'Industriestandorte für CCS-Anwendungen.1',
       'Industriestandorte für Wasserstoffanwendungen.1',
       'Windkraftanlagen Neubau.1',
       'Stromtrassen-Übertragungssnetze (oberiridisch).1',
       'CO2-Hauptleitung Neubau.1', 'Wasserstoffkernnetz Umbau .1',
       'Wasserstoffkernnetz Neubau .1',
       'Stromtrassen-Übertragungsnetze (unterirdisch).1',
       'Solarparks Neubau.1'],
      dtype='object')

In [61]:
data.sort_values(by='Transformationsindex Infrastrukturrelevanz', inplace=True, ascending=False)
data

,Postleitzahlgebiet,Transformationsindex Infrastrukturrelevanz,Industriestandorte für CCS-Anwendungen,Industriestandorte für Wasserstoffanwendungen,Windkraftanlagen Neubau,Stromtrassen-Übertragungssnetze (oberiridisch),CO2-Hauptleitung Neubau,Wasserstoffkernnetz Umbau,Wasserstoffkernnetz Neubau,Stromtrassen-Übertragungsnetze (unterirdisch),...,Transformationsindex Infrastrukturrelevanz.1,Industriestandorte für CCS-Anwendungen.1,Industriestandorte für Wasserstoffanwendungen.1,Windkraftanlagen Neubau.1,Stromtrassen-Übertragungssnetze (oberiridisch).1,CO2-Hauptleitung Neubau.1,Wasserstoffkernnetz Umbau .1,Wasserstoffkernnetz Neubau .1,Stromtrassen-Übertragungsnetze (unterirdisch).1,Solarparks Neubau.1
0,47179,0.377519,1.000000,1.000000,0.0,0.000000,0.000000,0.327135,0.550565,0.0,...,stark relevant,stark relevant,stark relevant,nicht relevant,nicht relevant,nicht relevant,stark relevant,stark relevant,nicht relevant,nicht relevant
1,67069,0.180774,0.150567,0.494407,0.0,0.452282,0.000000,0.000000,0.296398,0.0,...,stark relevant,relevant,stark relevant,nicht relevant,stark relevant,nicht relevant,nicht relevant,stark relevant,nicht relevant,nicht relevant
2,68549,0.158929,0.000000,0.000000,0.0,0.783739,0.000000,0.000000,0.621811,0.0,...,stark relevant,nicht relevant,nicht relevant,nicht relevant,stark relevant,nicht relevant,nicht relevant,stark relevant,nicht relevant,nicht relevant
3,50997,0.158623,0.542247,0.004520,0.0,0.267924,0.069743,0.000000,0.336867,0.0,...,stark relevant,stark relevant,sehr schwach relevant,nicht relevant,relevant,schwach relevant,nicht relevant,stark relevant,nicht relevant,nicht relevant
4,47166,0.150743,0.109617,0.113599,0.0,0.000000,0.000000,0.299056,0.942508,0.0,...,stark relevant,schwach relevant,schwach relevant,nicht relevant,nicht relevant,nicht relevant,stark relevant,stark relevant,nicht relevant,nicht relevant
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8174,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8175,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8176,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8177,NaN,NaN,NaN,NaN,NaN,6092.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
data_top_100=data.head(1000)
data_top_100["Postleitzahlgebiet"]=data_top_100["Postleitzahlgebiet"].astype(str)
data_top_100["join_key"] = data_top_100["Postleitzahlgebiet"].str.zfill(5)

/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_32905/2988427372.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_top_100["Postleitzahlgebiet"]=data_top_100["Postleitzahlgebiet"].astype(str)
/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_32905/2988427372.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_top_100["join_key"] = data_top_100["Postleitzahlgebiet"].str.zfill(5)

In [63]:
import geopandas as gpd

In [64]:
plz_shapes=gpd.read_file("/Users/halukamaier-borst/Documents/CodeRelated/HBDataviz_HalukaOnly/2026/01_IWKarte/Wrangle/data/PLZDaten/02_Shape/PLZ_5_Flaeche_region.shp")
plz_shapes

      Plz_5                                           geometry
0     01067  POLYGON ((828855.749 5667442.378, 828846.901 5...
1     01069  POLYGON ((830227.115 5664838.099, 830237.241 5...
2     01097  POLYGON ((830944.223 5668036.618, 830947.2 566...
3     01099  POLYGON ((832489.272 5670946.565, 832775.988 5...
4     01108  POLYGON ((833001.883 5680161.949, 833131.59 56...
...     ...                                                ...
8163  99988  POLYGON ((586382.277 5671246.424, 586445.333 5...
8164  99991  POLYGON ((604602.683 5667215.165, 606098.627 5...
8165  99994  POLYGON ((614751.998 5682921.318, 615355.305 5...
8166  99996  POLYGON ((603346.478 5689047.421, 603442.69 56...
8167  99998  POLYGON ((605957.862 5678814.084, 605967.023 5...

[8168 rows x 2 columns]

In [65]:
plz_shapes = plz_shapes.set_crs(epsg=3044,allow_override=True)

plz_shapes = plz_shapes.to_crs(epsg=4326)
plz_shapes

      Plz_5                                           geometry
0     01067  POLYGON ((13.69416 51.0641, 13.6941 51.06475, ...
1     01069  POLYGON ((13.71129 51.03997, 13.71146 51.04022...
2     01097  POLYGON ((13.7244 51.06823, 13.72445 51.06824,...
3     01099  POLYGON ((13.74905 51.09341, 13.75328 51.09462...
4     01108  POLYGON ((13.76486 51.1757, 13.76673 51.17582,...
...     ...                                                ...
8163  99988  POLYGON ((10.23602 51.1861, 10.23692 51.18595,...
8164  99991  POLYGON ((10.49547 51.14682, 10.51694 51.14928...
8165  99994  POLYGON ((10.64554 51.28605, 10.65415 51.28485...
8166  99996  POLYGON ((10.48382 51.3433, 10.48521 51.34335,...
8167  99998  POLYGON ((10.51826 51.25083, 10.51852 51.25455...

[8168 rows x 2 columns]

In [66]:
plz_shapes["join_key"] = plz_shapes["Plz_5"].astype(str)
data_top_100["join_key"]  = data_top_100["Postleitzahlgebiet"].astype(str)
data_top_100

/var/folders/d_/6z_vk0mx7j10g1h2zrjh_6f00000gn/T/ipykernel_32905/57292640.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_top_100["join_key"]  = data_top_100["Postleitzahlgebiet"].astype(str)

,Postleitzahlgebiet,Transformationsindex Infrastrukturrelevanz,Industriestandorte für CCS-Anwendungen,Industriestandorte für Wasserstoffanwendungen,Windkraftanlagen Neubau,Stromtrassen-Übertragungssnetze (oberiridisch),CO2-Hauptleitung Neubau,Wasserstoffkernnetz Umbau,Wasserstoffkernnetz Neubau,Stromtrassen-Übertragungsnetze (unterirdisch),...,Industriestandorte für CCS-Anwendungen.1,Industriestandorte für Wasserstoffanwendungen.1,Windkraftanlagen Neubau.1,Stromtrassen-Übertragungssnetze (oberiridisch).1,CO2-Hauptleitung Neubau.1,Wasserstoffkernnetz Umbau .1,Wasserstoffkernnetz Neubau .1,Stromtrassen-Übertragungsnetze (unterirdisch).1,Solarparks Neubau.1,join_key
0,47179,0.377519,1.000000,1.000000,0.000000,0.000000,0.000000,0.327135,0.550565,0.000000,...,stark relevant,stark relevant,nicht relevant,nicht relevant,nicht relevant,stark relevant,stark relevant,nicht relevant,nicht relevant,47179
1,67069,0.180774,0.150567,0.494407,0.000000,0.452282,0.000000,0.000000,0.296398,0.000000,...,relevant,stark relevant,nicht relevant,stark relevant,nicht relevant,nicht relevant,stark relevant,nicht relevant,nicht relevant,67069
2,68549,0.158929,0.000000,0.000000,0.000000,0.783739,0.000000,0.000000,0.621811,0.000000,...,nicht relevant,nicht relevant,nicht relevant,stark relevant,nicht relevant,nicht relevant,stark relevant,nicht relevant,nicht relevant,68549
3,50997,0.158623,0.542247,0.004520,0.000000,0.267924,0.069743,0.000000,0.336867,0.000000,...,stark relevant,sehr schwach relevant,nicht relevant,relevant,schwach relevant,nicht relevant,stark relevant,nicht relevant,nicht relevant,50997
4,47166,0.150743,0.109617,0.113599,0.000000,0.000000,0.000000,0.299056,0.942508,0.000000,...,schwach relevant,schwach relevant,nicht relevant,nicht relevant,nicht relevant,stark relevant,stark relevant,nicht relevant,nicht relevant,47166
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,39326,0.022309,0.000000,0.000000,0.000000,0.108549,0.016630,0.038837,0.000000,0.055689,...,nicht relevant,nicht relevant,nicht relevant,schwach relevant,sehr schwach relevant,sehr schwach relevant,nicht relevant,schwach relevant,nicht relevant,39326
996,97990,0.022307,0.000000,0.000000,0.000000,0.186385,0.000000,0.000000,0.000000,0.000000,...,nicht relevant,nicht relevant,nicht relevant,relevant,nicht relevant,nicht relevant,nicht relevant,nicht relevant,nicht relevant,97990
997,26131,0.022306,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.212973,0.000000,...,nicht relevant,nicht relevant,nicht relevant,nicht relevant,nicht relevant,nicht relevant,relevant,nicht relevant,nicht relevant,26131
998,99869,0.022281,0.000000,0.000000,0.019191,0.104280,0.000000,0.118251,0.000000,0.000000,...,nicht relevant,nicht relevant,sehr schwach relevant,schwach relevant,nicht relevant,schwach relevant,nicht relevant,nicht relevant,sehr schwach relevant,99869
999,54429,0.022248,0.000000,0.000000,0.181713,0.000000,0.000000,0.000000,0.000000,0.000000,...,nicht relevant,nicht relevant,relevant,nicht relevant,nicht relevant,nicht relevant,nicht relevant,nicht relevant,nicht relevant,54429

In [67]:


merged = plz_shapes.merge(data_top_100, on="join_key", how="inner")   # or how="inner" if you only want matches
merged["geometry"] = merged.geometry.simplify(0.001, preserve_topology=True)
merged

,Plz_5,geometry,join_key,Postleitzahlgebiet,Transformationsindex Infrastrukturrelevanz,Industriestandorte für CCS-Anwendungen,Industriestandorte für Wasserstoffanwendungen,Windkraftanlagen Neubau,Stromtrassen-Übertragungssnetze (oberiridisch),CO2-Hauptleitung Neubau,...,Transformationsindex Infrastrukturrelevanz.1,Industriestandorte für CCS-Anwendungen.1,Industriestandorte für Wasserstoffanwendungen.1,Windkraftanlagen Neubau.1,Stromtrassen-Übertragungssnetze (oberiridisch).1,CO2-Hauptleitung Neubau.1,Wasserstoffkernnetz Umbau .1,Wasserstoffkernnetz Neubau .1,Stromtrassen-Übertragungsnetze (unterirdisch).1,Solarparks Neubau.1
0,01097,"POLYGON ((13.7244 51.06823, 13.73521 51.07172,...",01097,01097,0.026523,0.0,0.0,0.000000,0.000000,0.235448,...,schwach relevant,nicht relevant,nicht relevant,nicht relevant,nicht relevant,relevant,nicht relevant,nicht relevant,nicht relevant,nicht relevant
1,01139,"POLYGON ((13.69829 51.0934, 13.70067 51.09549,...",01139,01139,0.027980,0.0,0.0,0.000000,0.000000,0.217906,...,schwach relevant,nicht relevant,nicht relevant,nicht relevant,nicht relevant,relevant,nicht relevant,nicht relevant,nicht relevant,sehr schwach relevant
2,01640,"POLYGON ((13.53738 51.15333, 13.54973 51.14754...",01640,01640,0.023805,0.0,0.0,0.000000,0.000000,0.121087,...,schwach relevant,nicht relevant,nicht relevant,nicht relevant,nicht relevant,schwach relevant,relevant,nicht relevant,nicht relevant,sehr schwach relevant
3,03149,"POLYGON ((14.49203 51.77484, 14.49469 51.77781...",03149,03149,0.026494,0.0,0.0,0.086607,0.000000,0.000000,...,schwach relevant,nicht relevant,nicht relevant,schwach relevant,nicht relevant,nicht relevant,nicht relevant,schwach relevant,nicht relevant,schwach relevant
4,03159,"POLYGON ((14.55953 51.64921, 14.56545 51.66577...",03159,03159,0.033449,0.0,0.0,0.273198,0.000000,0.000000,...,schwach relevant,nicht relevant,nicht relevant,relevant,nicht relevant,nicht relevant,nicht relevant,nicht relevant,nicht relevant,nicht relevant
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,99819,"POLYGON ((10.21461 51.02523, 10.22584 51.02976...",99819,99819,0.057515,0.0,0.0,0.000000,0.480552,0.000000,...,relevant,nicht relevant,nicht relevant,nicht relevant,stark relevant,nicht relevant,nicht relevant,nicht relevant,nicht relevant,nicht relevant
996,99820,"POLYGON ((10.37892 51.02205, 10.38323 51.02318...",99820,99820,0.023600,0.0,0.0,0.018999,0.079558,0.000000,...,schwach relevant,nicht relevant,nicht relevant,sehr schwach relevant,schwach relevant,nicht relevant,schwach relevant,schwach relevant,nicht relevant,sehr schwach relevant
997,99834,"POLYGON ((10.02108 50.99328, 10.02836 51.00269...",99834,99834,0.039899,0.0,0.0,0.000000,0.062398,0.000000,...,schwach relevant,nicht relevant,nicht relevant,nicht relevant,schwach relevant,nicht relevant,schwach relevant,nicht relevant,relevant,nicht relevant
998,99867,"POLYGON ((10.6454 50.9676, 10.65138 50.97395, ...",99867,99867,0.023034,0.0,0.0,0.000000,0.043237,0.000000,...,schwach relevant,nicht relevant,nicht relevant,nicht relevant,sehr schwach relevant,nicht relevant,relevant,nicht relevant,nicht relevant,sehr schwach relevant
999,99869,"POLYGON ((10.61415 51.03929, 10.61734 51.03858...",99869,99869,0.022281,0.0,0.0,0.019191,0.104280,0.000000,...,schwach relevant,nicht relevant,nicht relevant,sehr schwach relevant,schwach relevant,nicht relevant,schwach relevant,nicht relevant,nicht relevant,sehr schwach relevant

In [68]:

# (Optional) Reproject before export (GeoJSON often expected in WGS84)

# 4) Write to GeoJSON
merged.to_file("output2.geojson", driver="GeoJSON")

In [69]:
dissolved_gdf = merged.dissolve()
dissolved_gdf.to_file("dissolved.geojson", driver="GeoJSON")